---
AWSTemplateFormatVersion: '2010-09-09'

Description: S3 sourced Lambda function

Parameters:
  BucketName:
    Type: String
  VersionId:
    Type: String

Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        -
          PolicyName: AllowCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Responds with a throw of a dice
      Role: !GetAtt FunctionRole.Arn
      Timeout: 5 # seconds
      MemorySize: 128 # MB
      Runtime: python3.8
      Handler: index.lambda_handler
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda.zip
        S3ObjectVersion: !Ref VersionId

Outputs:
  LambdaName:
    Value: !Ref Function
