---
AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Serverless Application Model based Lambda function

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
      Timeout: 5 # seconds
      MemorySize: 128 # MB
      Runtime: python3.8
      Handler: index.lambda_handler
      CodeUri: ../source/
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  Url:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}
