version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --template-file lambda-templates/sam-lambda.yml --output-template-file package.yml
artifacts:
  files:
    - package.yml
