version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install jq zip
  build:
    commands:
      - cd source
      - zip -r9 ../lambda.zip *
      - cd ..
      - aws s3api put-object --bucket $S3_BUCKET --key lambda.zip --server-side-encryption aws:kms --body lambda.zip > response.json
      - cat response.json
      - cat response.json | jq --arg S3_BUCKET $S3_BUCKET '{"Parameters":{"VersionId":.VersionId,"BucketName":$S3_BUCKET}}' > configuration.json
      - cat configuration.json
artifacts:
  files:
    - configuration.json
